[workspace]
authors = ["Francesco Frassinelli <francesco.frassinelli@nina.no>"]
channels = ["conda-forge"]
name = "duckdb-bug"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
gcc = ">=15.2.0,<15.3"
cmake = ">=4.1.2,<5"
ninja = ">=1.13.1,<2"
python = ">=3.14.0,<3.15"
git = ">=2.51.1,<3"
gxx = ">=15.2.0,<15.3"
